/** Countries offered at checkout (ISO 3166-1 alpha-2). Edit to match where you ship. */
export const COUNTRIES: { code: string; name: string }[] = [
  ["US", "United States"],
  ["CA", "Canada"],
  ["GB", "United Kingdom"],
  ["IE", "Ireland"],
  ["IL", "Israel"],
  ["DE", "Germany"],
  ["FR", "France"],
  ["NL", "Netherlands"],
  ["BE", "Belgium"],
  ["LU", "Luxembourg"],
  ["ES", "Spain"],
  ["PT", "Portugal"],
  ["IT", "Italy"],
  ["AT", "Austria"],
  ["CH", "Switzerland"],
  ["DK", "Denmark"],
  ["SE", "Sweden"],
  ["NO", "Norway"],
  ["FI", "Finland"],
  ["PL", "Poland"],
  ["CZ", "Czechia"],
  ["GR", "Greece"],
  ["CY", "Cyprus"],
  ["RO", "Romania"],
  ["HU", "Hungary"],
  ["AU", "Australia"],
  ["NZ", "New Zealand"],
  ["JP", "Japan"],
  ["KR", "South Korea"],
  ["SG", "Singapore"],
  ["HK", "Hong Kong"],
  ["AE", "United Arab Emirates"],
  ["ZA", "South Africa"],
  ["BR", "Brazil"],
  ["MX", "Mexico"],
].map(([code, name]) => ({ code: code!, name: name! }));
